---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: st-test
spec:
  serviceAccountName: bitnami-secret-reader-sa
  inputResources:
  - name: aa940d4a-c022-4dae-ba69-fa01614154a0
    ref:
      apiVersion: v1
      kind: Secret
      name: aa940d4a-c022-4dae-ba69-fa01614154a0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitnami-secret-reader-sa

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: bitnami-secret-reader-role
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   verbs:
#   - get
#   - list
#   - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitnami-secret-reader-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bitnami-secret-reader-role
subjects:
- kind: ServiceAccount
  name: bitnami-secret-reader-rb